### ISSUE TITLE
Possible Solution to automatic EfConfig registrations

### ISSUE THREAD

**Issue by jeffward01** [Informatievlaanderen/ef-entity-configuration#176]
Hello!

I am trying to understand the purpose of your library.  Why not just do something like this:

````csharp
   var efConfig = this.GetType()
            .Assembly;
        modelBuilder.ApplyConfigurationsFromAssembly(efConfig);
````

If will look like this:

````csharp
public partial class PlaygroundHttpApiDbContext
{
    public DbSet<UserProfile> UserProfiles { get; set; }
    public DbSet<FollowUser> FollowUsers { get; set; }

 protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        BaseApplyEfConfigurations(modelBuilder);
    }


    private void BaseApplyEfConfigurations(ModelBuilder modelBuilder)
    {
        Guard.Against.Null(modelBuilder, nameof(modelBuilder));
        var efConfig = this.GetType()
            .Assembly;
        modelBuilder.ApplyConfigurationsFromAssembly(efConfig);
    }
}

````

Can you help me understand the purpose of your library?

**Comment by ArneD** [comment]
Hi @jeffward01,

A bit late (didn't get a notification), but we are currently revisiting this library and see if it's still needed.
I think (not sure about this), that this library was created because dotnet didn't have the functionality in net core 2.x.

If we do find a use case, I'll post it here, if not we will probably archive this repo.

**Comment by ArneD** [comment]
Repository is archived
